### ISSUE TITLE
Don't rebuild docker images per submission

### ISSUE THREAD

**Issue by ankitson** [proegssilb/ferris-elf#15]
We don't need to build a new docker image per submission. Instead we can build a docker image just once with rust and all our packages installed, then copy the user code and input into this image and execute it. Something like this:

```
$ docker run rust-runner cargo build
<wait until exit>
$ docker run --mount /a/b:/input/file.txt rust-runner cargo run --bin=tester
<wait until exit>
```

The initial image would have an entrypoint that spins and waits so it won't auto exit. 

Building a docker image and installing the rust toolchain on it is somewhat expensive (would take a few minutes to build at least) so this is preferable.

We would copy the input files into the image after building the user code but before executing it, to avoid potential issues with macros being used to read the input at compile time.

**Comment by proegssilb** [comment]
> The initial image would have an entrypoint that spins and waits so it won't auto exit.

If we go with running the same image twice, wouldn't we want the ENTRYPOINT to just be plain old `bash -c`? If we use an alternative ENTRYPOINT that never exits, then how would we know that `cargo build` has completed?

If we were using `docker exec`, you'd be correct. But working with `docker exec` requires additional work, because the bot doesn't already know how to chain commands and wait for their completion via `docker exec`.

While the extra container start-up/shut-down costs are a concern, I've timed podman running `cargo build` in `rust:latest` at ~2.25s on my desktop, with container removal. I'm not worried about that just yet, but if there's an easy way to make `docker exec` work to avoid container startup and teardown costs without costing too much dev time, I'm not opposed.

**Comment by proegssilb** [comment]
.....Actually, something clever we can do:

```
docker run --rm rust:latest sleep 5m
docker exec <cid> cargo build
[copy input files into container somehow]
docker exec <cid> cargo run
```

The `run` command sets pid0, so the entire container shuts down at the end of the `sleep` command. This ensures a timeout is observed by the docker runtime for the entire rust build + run process.

I have not yet figured out a way to capture command status nor stdin/stdout from `docker exec`.

**Comment by ankitson** [comment]
I love the `sleep` idea and tested it - works well!

The `docker-py` lib also looks to have support for getting both the exit status & direct streams of stdout/stderr from the container: https://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.Container.exec_run

**Comment by proegssilb** [comment]
Bumping the priority on this to 0.1 because we ran out of disk space in the QA VM due to docker containers and a small disk.
